export const competitions = [
  {
    slug: "calisthenics-cup-2026",
    name: "Calisthenics Cup 2026",
    startDate: "2026-04-16",
    endDate: "2026-04-19",
    city: "Cologne",
    country: "Germany",
    poster: "https://calisthenics-cup.com/wp-content/uploads/2024/01/IMG_6845-scaled.jpg",
    description: "The Calisthenics Cup will be held from April 16th to 19th, 2026, at the FIBO fitness convention in Cologne. The main competition events will take place on April 17-18th (Endurance) and 18th (freestyle). Athletes interested in participating in the Freestyle Calisthenics or Endurance Competitions can apply through the official website. Please ensure you meet the competition criteria and submit your application before the deadline. There are only 12 freestyle spots for men, 6 freestyle spots for women and 12 endurance spots for men and 6 spots for women endurance.",
    website: "https://calisthenics-cup.com",
    instagram: null,
    youtube: null,
    results: null
  },
  {
    slug: "calisthenics-world-championship-2026",
    name: "Calisthenics World Championship 2026",
    startDate: "2026-06-12",
    endDate: "2026-06-14",
    city: "Rome",
    country: "Italy",
    poster: "https://wswcf.org/wp-content/uploads/2026/01/logo_italia_2026-1_page-0001.jpg",
    description: "Organized by (Local Organizing Committee - LOC): ASD Eagle Association together with Federazione Nazionale Liberi Circoli (FENALC). Under the patronage of: Sport e Salute S.p.A.",
    website: "https://wswcf.org/",
    instagram: null,
    youtube: null,
    results: null
  },
  {
    slug: "ground-zero-championship-2026",
    name: "Ground Zero Championship 2026",
    startDate: "2026-01-09",
    endDate: "2026-01-10",
    city: "Bangalore",
    country: "India",
    poster: "/groundzero_2026.jpg",
    description: "National Level Calisthenics Championship🏆 Hosted by Limitless Calisthenics",
    website: "https://groundzeroweb.netlify.app/",
    instagram: "https://www.instagram.com/groundzerochampionship/",
    youtube: null,
    results: null
  },
  {
    slug: "sthenos-xbition-3",
    name: "Sthenos Xbition 3",
    startDate: "2025-05-30",
    endDate: "2025-05-30",
    city: "Lausanne",
    country: "Switzerland",
    poster: "/sthenos_3.jpg",
    description: "The Sports Festival is one of the world's top Street Workout and Calisthenics Championships, bringing together elite athletes and thousands of spectators for an unforgettable multi-sport weekend. Featuring freestyle calisthenics, set & reps, Sthenos Strength War, weightlifting and powerlifting, the event showcases strength sports on the biggest stage.",
    website: "",
    instagram: "https://www.instagram.com/sthenosmovement/",
    youtube: "https://www.youtube.com/@sthenosmovement",
    results: null
  },
];
